[project]
name = "repo-eval-by-llm-agent"
version = "0.1.0"
description = "evaluate how easy it is to use a repo, automatically by an llm agent."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.74.0",
]
